# Site settings
name: Sinliede
email: 932502163@qq.com
author: Sinliede
url: https://Sinliede.github.io/
resume_site: https://Sinliede.github.io/
github: https://github.com/Sinliede/
baseurl: ""
description: Some discoveries and ideas on coding
meta_description: Sinliede's personal blog, keep on going
motto: It's our wits that make us men.
banner: keep on going

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Sinliede

# Build settings
markdown: atom & typora

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

