title: Sinliede
description: My Personal Blog
author: Sinliede
logo: /static/img/sinliede.png
github: https://github.com/Sinliede
about: java developer

baseurl: "https://github.com/Sinliede"
url: "https://github.com/Sinliede/Sinliede.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
